name: py313-mlops
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - icu=75.1
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - ncurses=6.5
  - openssl=3.5.2
  - pip=25.2
  - python=3.13.5
  - python_abi=3.13
  - readline=8.2
  - tk=8.6.13
  - tzdata=2025b
