apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: health-insurance-charge-api-servicemonitor
  labels:
    release: prom # Match the label of your Prometheus instance as per helm release
spec:
  selector:
    matchLabels:
      app: api
  namespaceSelector:
    matchNames:
      - default # or your namespace
  endpoints:
    - port: "8000" # or match name of your service port
      path: /metrics
      interval: 15s
