# mlflow
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5555:5000"
    command: |
      sh -c "
      mkdir -p /mlflow/mlruns /mlflow/artifacts &&
      chmod -R 777 /mlflow &&
      mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow/mlflow.db --artifacts-destination /mlflow/artifacts --serve-artifacts
      "
    container_name: mlflow-tracking-server
    volumes:
      - mlflow-data:/mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
      - MLFLOW_ARTIFACTS_DESTINATION=/mlflow/artifacts

volumes:
  mlflow-data:
    driver: local
