apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
  - name: "8000"
    nodePort: 30100
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: "metrics"
    port: 9100
    targetPort: 9100
  selector:
    app: api
  type: NodePort
status:
  loadBalancer: {}
