apiVersion: v1
kind: Service
metadata:
  labels:
    app: streamlit-latest
  name: streamlit-latest
spec:
  ports:
  - name: "8501"
    nodePort: 30000
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: streamlit-latest
  type: NodePort
status:
  loadBalancer: {}
