apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit-latest
  name: streamlit-latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-latest
  strategy: {}
  template:
    metadata:
      labels:
        app: streamlit-latest
    spec:
      containers:
      - image: shuaiba8/streamlit:latest-v2
        imagePullPolicy: Always
        name: streamlit
        ports:
        - containerPort: 8501
        resources: {}
status: {}
