best_model_name: 
  XGBRegressor
best_model_params:
  learning_rate: 0.2
  max_depth: 3
  n_estimators: 80
selected_features:
- age
- bmi
- children
- sex
- smoker
- region
target_variable: 
  charges
performance:
  r2: 0.8979585648487498
  mae: 2540.426183088474
  rmse: 4330.211599044418
  mse: 18750732.49249882
