name: MLOps CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.11'

      - name: Install dependencies
        run: |
          uv venv
          uv sync --frozen --no-dev

      - name: Install package
        run: |
          uv pip install -e .

      - name: Run feature engineering (ordinal encoding featureset)
        run: |
          uv run python src/features/engineer.py \
          --input data/interim/cleaned_health_insurance_us_v1.csv \
          --output data/processed/clean_feature_process_ordinal_health_insurance_us_v1.csv \
          --preprocessor models/trained/preprocessor_ordinal_clean.pkl \
          --encoding ordinal

      - name: Setup MLflow
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d -p 5555:5000 --name mlflow-tracking-server ghcr.io/mlflow/mlflow:latest \
          --backend-store-uri sqlite:///mlflow/mlflow.db \ 
          --artifacts-destination /mlflow/artifacts \ 
          --serve-artifacts

      - name: Train the model 
        run: |
          uv run python src/models/train.py \
          --config configs/model_config.yaml \
          --data data/processed/clean_feature_process_ordinal_health_insurance_us_v1.csv \
          --models-dir models/ \
          --mlflow_tracking_uri http://localhost:5555 \
